var annotated =
[
    [ "client", "d7/d1c/namespaceclient.xhtml", "d7/d1c/namespaceclient" ],
    [ "K4U", "d6/d75/namespace_k4_u.xhtml", "d6/d75/namespace_k4_u" ],
    [ "QtJson", "d2/d6d/namespace_qt_json.xhtml", null ],
    [ "shared", "de/d48/namespaceshared.xhtml", "de/d48/namespaceshared" ],
    [ "Ui", "dc/df0/namespace_ui.xhtml", "dc/df0/namespace_ui" ],
    [ "Controllingroomba", "dc/dd3/class_controllingroomba.xhtml", "dc/dd3/class_controllingroomba" ],
    [ "DisplayLogs", "df/d99/class_display_logs.xhtml", "df/d99/class_display_logs" ],
    [ "Information", "d1/d35/class_information.xhtml", "d1/d35/class_information" ],
    [ "myTimer", "d3/d2f/classmy_timer.xhtml", "d3/d2f/classmy_timer" ],
    [ "qt_meta_stringdata_client__clsServerConn_t", "d9/d5b/structqt__meta__stringdata__client____cls_server_conn__t.xhtml", "d9/d5b/structqt__meta__stringdata__client____cls_server_conn__t" ],
    [ "qt_meta_stringdata_Controllingroomba_t", "d9/d56/structqt__meta__stringdata___controllingroomba__t.xhtml", "d9/d56/structqt__meta__stringdata___controllingroomba__t" ],
    [ "qt_meta_stringdata_DisplayLogs_t", "d5/d7d/structqt__meta__stringdata___display_logs__t.xhtml", "d5/d7d/structqt__meta__stringdata___display_logs__t" ],
    [ "qt_meta_stringdata_Information_t", "df/d99/structqt__meta__stringdata___information__t.xhtml", "df/d99/structqt__meta__stringdata___information__t" ],
    [ "qt_meta_stringdata_Roomba_t", "dd/da8/structqt__meta__stringdata___roomba__t.xhtml", "dd/da8/structqt__meta__stringdata___roomba__t" ],
    [ "qt_meta_stringdata_SettingsRoomba_t", "db/d7f/structqt__meta__stringdata___settings_roomba__t.xhtml", "db/d7f/structqt__meta__stringdata___settings_roomba__t" ],
    [ "Roomba", "d5/d2a/class_roomba.xhtml", "d5/d2a/class_roomba" ],
    [ "SettingsRoomba", "d1/d84/class_settings_roomba.xhtml", "d1/d84/class_settings_roomba" ],
    [ "Ui_Controllingroomba", "d3/d58/class_ui___controllingroomba.xhtml", "d3/d58/class_ui___controllingroomba" ],
    [ "Ui_DisplayLogs", "db/dfa/class_ui___display_logs.xhtml", "db/dfa/class_ui___display_logs" ],
    [ "Ui_Information", "dc/d24/class_ui___information.xhtml", "dc/d24/class_ui___information" ],
    [ "Ui_Roomba", "d8/de5/class_ui___roomba.xhtml", "d8/de5/class_ui___roomba" ],
    [ "Ui_SettingsRoomba", "d5/d57/class_ui___settings_roomba.xhtml", "d5/d57/class_ui___settings_roomba" ]
];