Makefile_TARGETS = \
	Makefile.dep \
	src/Makefile \
	build/Makefile

Makefile_DEPS = \
	E:/repositories/git/ese_project4y5/Hoofdprogramma/test.rtmdl \
	C:/Program\ Files\ (x86)/Rational/Rose\ RealTime/C++/RTComponents.rtcmppkg \
	C:/Program\ Files\ (x86)/Rational/Rose\ RealTime/C++/RTClasses.rtlogpkg

